server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./temp-h2-store
    driverClasName: org.h2.Driver
    username: min
    password: max
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: false
        dialect: org.hibernate.dialect.H2Dialect
#  servlet:
#    multipart:
#      file-size-threshold: 2KB
#      max-file-size: 20MB
#      max-request-size: 25MB
